name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/next-auth-without-next-auth

            echo "Checking if .env file exists..."
            if [ ! -f .env ]; then
              echo "Generating .env from GitHub Secrets..."
              echo "DATABASE_URL=file:./dev.db" >> .env
              echo "GITHUB_CLIENT_ID=${{ secrets.GB_CLIENT_ID }}" >> .env
              echo "GITHUB_CLIENT_SECRET=${{ secrets.GB_CLIENT_SECRET }}" >> .env
            else
              echo ".env already exists. Skipping secret injection."
            fi

            echo "Pulling latest code and rebuilding..."
            git pull
            docker compose up -d --build
